package de.ax.powermode.power.color;

import javax.swing.*;
import java.awt.*;

/**
 * Created by nyxos on 21.06.16.
 */
public class UiTest {
    private JPanel colorView;
    private JPanel root;


    static double c = 0;
    static double f = 60.0;
    static double x = (255 / 5000.0) * f;

    public static void main(String[] args) {
        JFrame frame = new JFrame("UiTest");
        UiTest uiTest = new UiTest();
        frame.setContentPane(uiTest.root);
        frame.setSize(500, 500);

        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);


    }

    private void createUIComponents() {
//        colorView = new MultiGradientPanel(500, new ColorEdges());
//        new ColorViewController((MultiGradientPanel) colorView);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        root = new JPanel();
        root.setLayout(new BorderLayout(0, 0));
        root.add(colorView, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }
}
